-- AlterEnum
ALTER TYPE "AnalyticsEventName" ADD VALUE 'VERSION_ADDED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'COMMENT_ADDED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'LIVE_REVIEW_STARTED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'LIVE_REVIEW_JOINED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'APPROVAL_REQUESTED';
