import type { CompetitorProfile, CompetitorSource } from '@/lib/marketing/comparison-types';

const LAST_CHECKED = '2026-06-14';

export const competitorSources: CompetitorSource[] = [
  {
    competitor: 'frame-io',
    sourceUrl: 'https://frame.io/pricing',
    sourceType: 'pricing',
    lastChecked: LAST_CHECKED,
    claims: [
      'Free plan: 2 members, 2GB storage, 2 projects.',
      'Pro: $15/member/month with 2TB included + 2TB per additional member.',
      'Team: $25/member/month with 3TB included + 2TB per additional member.',
    ],
    caveats: ['Pricing excludes tax. Enterprise is custom.'],
    confidence: 'high',
  },
  {
    competitor: 'frame-io',
    sourceUrl: 'https://help.frame.io/en/articles/9090642-getting-started-what-is-a-user',
    sourceType: 'help',
    lastChecked: LAST_CHECKED,
    claims: [
      'Reviewers can access media via share links without a Frame.io account.',
      'Reviewers are free and unlimited for external link-based review.',
      'Paid member seats are required for internal project management roles.',
    ],
    caveats: ['Guest users inside the account are limited on some plans.'],
    confidence: 'high',
  },
  {
    competitor: 'frame-io',
    sourceUrl: 'https://help.frame.io/en/articles/9105242-share-links-explained-for-clients',
    sourceType: 'help',
    lastChecked: LAST_CHECKED,
    claims: [
      'Share links support passphrase protection, expiration, download controls, and approval status.',
      'Commenting can be disabled per share link.',
    ],
    caveats: ['Some enterprise security features require higher tiers.'],
    confidence: 'high',
  },
  {
    competitor: 'wipster',
    sourceUrl: 'https://wipster.io/pricing',
    sourceType: 'pricing',
    lastChecked: LAST_CHECKED,
    claims: [
      'Light plan: $9.95/month annually or $11.95 monthly with 50GB storage.',
      'Team plan: $19.95/user/month annually or $25 monthly starting at 250GB.',
      'Unlimited reviewers on all plans.',
    ],
    caveats: ['Enterprise pricing is custom.'],
    confidence: 'high',
  },
  {
    competitor: 'wipster',
    sourceUrl: 'https://wipster.io/product',
    sourceType: 'product',
    lastChecked: LAST_CHECKED,
    claims: [
      'Supports video, image, PDF, and audio review.',
      'Version comparison, approval tracking, and NLE panel integrations.',
      'Public URL or private email sharing for reviewers.',
    ],
    caveats: ['SSO and org controls are enterprise features.'],
    confidence: 'high',
  },
  {
    competitor: 'dropbox-replay',
    sourceUrl: 'https://help.dropbox.com/create-upload/dropbox-replay-faq',
    sourceType: 'faq',
    lastChecked: LAST_CHECKED,
    claims: [
      'Replay is available on all Dropbox plans but free tiers have 4–10 file limits.',
      'Replay Add-On removes file creation/upload limits.',
      'Files uploaded from outside Dropbox count against Dropbox storage.',
    ],
    caveats: ['Replay Add-On requires a paid Dropbox plan.'],
    confidence: 'high',
  },
  {
    competitor: 'dropbox-replay',
    sourceUrl: 'https://www.dropbox.com/replay',
    sourceType: 'product',
    lastChecked: LAST_CHECKED,
    claims: [
      'Replay Add-On is about €9/user/month annually or €11 monthly.',
      'Integrates with Premiere Pro, After Effects, Final Cut Pro, DaVinci Resolve, and Avid Pro Tools.',
      'Supports version comparison, transcriptions, due dates, and password-protected links on paid add-on.',
    ],
    caveats: ['Requires Dropbox ecosystem buy-in.'],
    confidence: 'high',
  },
  {
    competitor: 'krock',
    sourceUrl: 'https://krock.io/pricing/',
    sourceType: 'pricing',
    lastChecked: LAST_CHECKED,
    claims: [
      'Free: 1 user, 2GB, 2 projects, unlimited reviewers.',
      'Pro: $10/user/month with 2TB storage and unlimited projects.',
      'Unlimited plan: flat $400/month for large teams.',
    ],
    caveats: ['Storage add-ons are $10/month per TB.'],
    confidence: 'high',
  },
  {
    competitor: 'krock',
    sourceUrl: 'https://krock.io/help-center/how-to-manage-team-members-collaborators-reviewers/',
    sourceType: 'help',
    lastChecked: LAST_CHECKED,
    claims: [
      'Reviewers can access projects via links without paid seats.',
      'Includes storyboard, animatic, and production workflow tooling.',
    ],
    caveats: ['Storyboard AI is newer and may not fit every pipeline.'],
    confidence: 'high',
  },
  {
    competitor: 'revcut',
    sourceUrl: 'https://revcut.io/pricing',
    sourceType: 'pricing',
    lastChecked: LAST_CHECKED,
    claims: [
      'Crew: €69/month with 8 seats and 3TB active storage.',
      'Studio: €149/month with 15 seats and 5TB active storage.',
      '14-day free trial with no credit card required.',
    ],
    caveats: ['Storage is designed for active review cycles, not long-term archiving.'],
    confidence: 'high',
  },
  {
    competitor: 'revcut',
    sourceUrl: 'https://revcut.io/client-video-review',
    sourceType: 'product',
    lastChecked: LAST_CHECKED,
    claims: [
      'Clients review via secure links with name-only access, no account required.',
      'Native DaVinci Resolve plugin for marker export.',
      'EU-hosted with GDPR-minded positioning.',
    ],
    caveats: ['Premiere/FCP integrations listed as coming later.'],
    confidence: 'high',
  },
  {
    competitor: 'vimeo-review',
    sourceUrl:
      'https://help.vimeo.com/hc/en-us/articles/12426192100113-How-to-use-and-manage-video-review-links',
    sourceType: 'help',
    lastChecked: LAST_CHECKED,
    claims: [
      'Review links work for people without a Vimeo account.',
      'Supports passwords, expiration, downloads, commenting, and approval status toggles.',
      'Guests provide name and email before commenting.',
    ],
    caveats: ['Folder review links require Standard plan or higher.'],
    confidence: 'high',
  },
  {
    competitor: 'vimeo-review',
    sourceUrl: 'https://vimeo.com/features/video-collaboration',
    sourceType: 'product',
    lastChecked: LAST_CHECKED,
    claims: [
      'Review is built into Vimeo hosting with version history and Premiere integration.',
      'Time-stamped comments with resolve workflow.',
    ],
    caveats: ['Best fit when you already host video on Vimeo.'],
    confidence: 'high',
  },
  {
    competitor: 'vitransfer',
    sourceUrl: 'https://www.vitransfer.com/docs',
    sourceType: 'docs',
    lastChecked: LAST_CHECKED,
    claims: [
      'AGPL-3.0 self-hosted video review and approval platform.',
      'Share links support password, email OTP, guest mode, and approval workflows.',
      'Guests are view-only by default; downloads gated until approval.',
    ],
    caveats: ['Requires Docker infrastructure and ongoing maintenance.'],
    confidence: 'high',
  },
  {
    competitor: 'freeframe',
    sourceUrl: 'https://github.com/Techiebutler/freeframe',
    sourceType: 'github',
    lastChecked: LAST_CHECKED,
    claims: [
      'Self-hosted open-source media review for video, image, and audio.',
      'Frame-accurate comments, annotations, approvals, version compare, and guest share links.',
      'Uses FastAPI backend with Next.js frontend and S3-compatible storage.',
    ],
    caveats: ['Requires external S3, SMTP, and production ops setup.'],
    confidence: 'high',
  },
  {
    competitor: 'flask',
    sourceUrl: 'https://flask.do/pricing',
    sourceType: 'pricing',
    lastChecked: LAST_CHECKED,
    claims: [
      'Free: $0, no card required, all features, 1 asset at a time.',
      'Pro: $15/user/month billed yearly; $0 per guest; unlimited uploads.',
      'Pro includes original file downloads for 30 days; enterprise from 15 seats.',
    ],
    caveats: ['Pro is billed yearly; enterprise pricing is custom.'],
    confidence: 'high',
  },
  {
    competitor: 'flask',
    sourceUrl: 'https://flask.do/',
    sourceType: 'product',
    lastChecked: LAST_CHECKED,
    claims: [
      'Voice-first feedback: record spoken notes while watching and Flask structures timestamped comments.',
      'Supports drawing, references, version compare, Drive import, and Premiere export.',
      'Positions upmarket for production teams of 5–100 people.',
    ],
    caveats: ['Free tier limits you to one active asset at a time.'],
    confidence: 'high',
  },
  {
    competitor: 'aligno',
    sourceUrl: 'https://aligno.io/pricing',
    sourceType: 'pricing',
    lastChecked: LAST_CHECKED,
    claims: [
      'Pro: $18/month or $180/year flat rate per creator.',
      'Clients never need accounts and do not count toward limits.',
      'Supports images, PDFs, videos, and webpages with explicit approval states.',
    ],
    caveats: ['Video review is one part of a broader multi-asset approval tool.'],
    confidence: 'high',
  },
  {
    competitor: 'videoreview-pro',
    sourceUrl: 'https://videoreview.pro/',
    sourceType: 'pricing',
    lastChecked: LAST_CHECKED,
    claims: [
      'Free forever with 30 minutes total video storage.',
      'Pro: $99/year with 10 hours of storage.',
      'All features included on both plans; only storage differs.',
    ],
    caveats: ['Very limited storage compared to production workflows.'],
    confidence: 'high',
  },
];

export const competitorProfiles: Record<string, CompetitorProfile> = {
  'frame-io': {
    id: 'frame-io',
    name: 'Frame.io',
    tagline: 'Enterprise creative operations platform with deep Adobe integration.',
    bestFor: [
      'Large post-production teams in Adobe Creative Cloud',
      'Studios needing enterprise security, DRM, and MAM workflows',
      'Teams that need Camera to Cloud and hardware integrations',
    ],
    strengths: [
      'Industry-standard Adobe Premiere and Final Cut integrations',
      'Mature share-link review with approvals, watermarks, and enterprise controls',
      'Transcription, captions, metadata, and broad asset management',
    ],
    limitations: [
      'Per-member pricing scales quickly for small teams',
      'Heavier platform than freelancers need for simple client approvals',
      'No self-hosting option for teams that need full data control',
    ],
    pricingSummary: 'Free (2GB) · Pro $15/member/mo · Team $25/member/mo',
    pricingNotes: [
      'External reviewers via share links are free.',
      'Paid seats are for team members managing projects inside Frame.io.',
    ],
    reviewerAccess:
      'Share links allow review without a Frame.io account; internal roles require paid seats.',
    selfHosted: false,
    sources: [
      'https://frame.io/pricing',
      'https://help.frame.io/en/articles/9090642-getting-started-what-is-a-user',
    ],
  },
  wipster: {
    id: 'wipster',
    name: 'Wipster',
    tagline: 'Video-first review and approval for agencies and production teams.',
    bestFor: [
      'Agencies managing multiple client review cycles',
      'Video teams wanting NLE panel integrations',
      'Teams that need unlimited external reviewers',
    ],
    strengths: [
      'Unlimited reviewers on every plan',
      'Side-by-side version comparison and approval tracking',
      'Premiere Pro and After Effects panel integrations',
    ],
    limitations: [
      'Per-user pricing on Team plans',
      'US-hosted SaaS with no self-host option',
      'Broader creative-ops features are lighter than Frame.io enterprise',
    ],
    pricingSummary: 'Light $9.95/mo · Team from $19.95/user/mo',
    pricingNotes: ['Free trial with no credit card required.', 'Enterprise is custom.'],
    reviewerAccess: 'Reviewers can use public links or email invites without paid seats.',
    selfHosted: false,
    sources: ['https://wipster.io/pricing', 'https://wipster.io/product'],
  },
  'dropbox-replay': {
    id: 'dropbox-replay',
    name: 'Dropbox Replay',
    tagline: 'Review and approval add-on inside the Dropbox ecosystem.',
    bestFor: [
      'Teams already storing and delivering files in Dropbox',
      'Editors who want NLE integrations tied to Dropbox storage',
      'Lightweight review without adopting a separate platform',
    ],
    strengths: [
      'Native integrations with Premiere, After Effects, FCP, Resolve, and Pro Tools',
      'Version comparison, transcriptions, and due dates on paid add-on',
      'Familiar Dropbox security and link management',
    ],
    limitations: [
      'Requires Dropbox plan plus Replay Add-On for full usage',
      'Free Replay tiers cap active files at 4–10 uploads',
      'Not a standalone review platform with its own project model',
    ],
    pricingSummary: 'Replay Add-On ~€9/user/mo annually',
    pricingNotes: [
      'Basic Replay is included but file-limited on most plans.',
      'Password protection and transcription require the paid add-on.',
    ],
    reviewerAccess: 'Collaborators review in browser; full value assumes Dropbox account context.',
    selfHosted: false,
    sources: [
      'https://www.dropbox.com/replay',
      'https://help.dropbox.com/create-upload/dropbox-replay-faq',
    ],
  },
  krock: {
    id: 'krock',
    name: 'Krock.io',
    tagline: 'Creative production workspace with storyboards, animatics, and review.',
    bestFor: [
      'Animation studios and pre-to-post production pipelines',
      'Teams wanting storyboard and animatic review in one tool',
      'Studios needing unlimited external reviewers',
    ],
    strengths: [
      'Storyboard and animatic tooling upstream of video review',
      'Unlimited reviewers on all plans',
      'Integrations with Adobe CC, Resolve, FCP, and Slack',
    ],
    limitations: [
      'Per-user pricing on Pro plan',
      'Broader production tooling may be more than solo freelancers need',
      'No self-hosting option',
    ],
    pricingSummary: 'Free · Pro $10/user/mo · Unlimited $400/mo flat',
    pricingNotes: ['7-day trial on paid plans.', 'Storage add-ons available.'],
    reviewerAccess: 'Guest review links without account creation.',
    selfHosted: false,
    sources: [
      'https://krock.io/pricing/',
      'https://krock.io/help-center/how-to-manage-team-members-collaborators-reviewers/',
    ],
  },
  revcut: {
    id: 'revcut',
    name: 'RevCut',
    tagline: 'EU-hosted video review built for editors and small post teams.',
    bestFor: [
      'EU-based editors needing GDPR-minded hosting',
      'DaVinci Resolve-first workflows',
      'Small teams wanting client review without logins',
    ],
    strengths: [
      'Clients review via secure links with name-only access',
      'Native DaVinci Resolve plugin',
      'Explicit EU hosting and privacy positioning',
    ],
    limitations: [
      'No self-hosting option',
      'Higher entry pricing than solo freelancer tools',
      'Premiere/FCP integrations still limited compared to Frame.io',
    ],
    pricingSummary: 'Crew €69/mo · Studio €149/mo',
    pricingNotes: ['14-day free trial.', 'Storage is for active review cycles.'],
    reviewerAccess: 'Clients use secure links with optional password; no account required.',
    selfHosted: false,
    sources: ['https://revcut.io/pricing', 'https://revcut.io/client-video-review'],
  },
  'vimeo-review': {
    id: 'vimeo-review',
    name: 'Vimeo Review',
    tagline: 'Review tools built into Vimeo video hosting.',
    bestFor: [
      'Teams already hosting and delivering on Vimeo',
      'Creators who want review without a second subscription',
      'Workflows centered on Vimeo distribution',
    ],
    strengths: [
      'Review links with no Vimeo account required for guests',
      'Version history, status labels, and Premiere integration',
      'Password and expiration controls on review links',
    ],
    limitations: [
      'Tied to Vimeo hosting plans',
      'Less focused on standalone approval workflows',
      'No self-hosting or open-source path',
    ],
    pricingSummary: 'Bundled with Vimeo Standard+ plans',
    pricingNotes: ['Folder review links require Standard plan or higher.'],
    reviewerAccess: 'External reviewers use review links without Vimeo accounts.',
    selfHosted: false,
    sources: [
      'https://vimeo.com/features/video-collaboration',
      'https://help.vimeo.com/hc/en-us/articles/12426192100113-How-to-use-and-manage-video-review-links',
    ],
  },
  vitransfer: {
    id: 'vitransfer',
    name: 'ViTransfer',
    tagline: 'AGPL self-hosted video review with approval workflows.',
    bestFor: [
      'Teams that want open-source and full infrastructure control',
      'Studios with Docker ops capacity',
      'Privacy-sensitive client work kept on owned hardware',
    ],
    strengths: [
      'No subscription fees beyond your own infrastructure',
      'Per-video approvals with download gating',
      'Password, email OTP, and guest access modes',
    ],
    limitations: [
      'Requires setup, maintenance, and transcoding resources',
      'Guest mode is view-only by default',
      'Smaller ecosystem than commercial incumbents',
    ],
    pricingSummary: 'Free (self-hosted, AGPL-3.0)',
    pricingNotes: ['Storage limited only by your own hardware.'],
    reviewerAccess: 'Share links with configurable auth; guest mode is view-only.',
    selfHosted: true,
    sources: ['https://www.vitransfer.com/docs', 'https://www.vitransfer.com/about'],
  },
  freeframe: {
    id: 'freeframe',
    name: 'FreeFrame',
    tagline: 'Self-hosted open-source media review platform.',
    bestFor: [
      'Teams wanting multi-format review on owned infrastructure',
      'Organizations with S3 and SMTP already in place',
      'Open-source adopters comparing to Frame.io',
    ],
    strengths: [
      'Video, image, and audio review in one platform',
      'Approvals, version compare, guest share links, and SSE updates',
      'Bring-your-own S3, Redis, and PostgreSQL',
    ],
    limitations: [
      'Production deployment requires DevOps effort',
      'Different stack (FastAPI + Next.js) from OpenFrame',
      'Younger project with smaller community',
    ],
    pricingSummary: 'Free (self-hosted, open source)',
    pricingNotes: ['Infrastructure and ops costs apply.'],
    reviewerAccess: 'Guest commenting via password-protected share links.',
    selfHosted: true,
    sources: ['https://github.com/Techiebutler/freeframe'],
  },
  flask: {
    id: 'flask',
    name: 'Flask',
    tagline: 'Voice-first video feedback that structures spoken notes automatically.',
    bestFor: [
      'Reviewers who prefer talking through feedback instead of typing',
      'Production teams of 5–100 people',
      'Teams exploring AI-assisted feedback workflows',
    ],
    strengths: [
      'Records spoken feedback and turns it into timestamped action items',
      'Drawing, references, version compare, and Premiere export',
      'MCP integration for agent-assisted workflows',
      'Free tier with full features (1 asset at a time)',
    ],
    limitations: [
      'No public self-host option',
      'Pro is $15/user/month billed yearly',
      'Free tier limited to one active asset',
      'Focused on feedback capture more than formal approval chains',
    ],
    pricingSummary: 'Free (1 asset) · Pro $15/user/mo (yearly) · Enterprise custom',
    pricingNotes: ['Pro includes $0 per guest and unlimited uploads.'],
    reviewerAccess: '$0 per guest on Pro; free tier for trying without a card.',
    selfHosted: false,
    sources: ['https://flask.do/pricing', 'https://flask.do/'],
  },
  aligno: {
    id: 'aligno',
    name: 'Aligno',
    tagline: 'Flat-rate multi-asset approval for designers and agencies.',
    bestFor: [
      'Designers and agencies reviewing video alongside images and PDFs',
      'Solo creators with many clients and no per-reviewer fees',
      'Teams wanting explicit approve/request-changes workflow',
    ],
    strengths: [
      'Flat per-creator pricing with unlimited free clients',
      'Multi-asset review in one workspace',
      'Explicit approval states on every version',
    ],
    limitations: [
      'Less depth for full-time post-production houses',
      'No self-hosting option',
      'Video tooling is narrower than dedicated review platforms',
    ],
    pricingSummary: 'Free · Pro $18/mo · Studio custom',
    pricingNotes: ['Clients never count toward seat limits.'],
    reviewerAccess: 'Clients review via share links without accounts.',
    selfHosted: false,
    sources: ['https://aligno.io/pricing', 'https://aligno.io/frame-io-alternative'],
  },
  'videoreview-pro': {
    id: 'videoreview-pro',
    name: 'VideoReview.pro',
    tagline: 'Minimal timestamped video feedback with a generous free tier.',
    bestFor: [
      'Creators needing basic timestamped comments on a budget',
      'Very small projects with limited storage needs',
      'Teams testing video review for the first time',
    ],
    strengths: [
      'Free forever with all features included',
      'Simple upload, share, and comment workflow',
      'Password-protected share links',
    ],
    limitations: [
      'Only 30 minutes free storage; Pro caps at 10 hours/year',
      'No formal approval workflow or version compare',
      'No self-hosting or open-source option',
    ],
    pricingSummary: 'Free (30 min) · Pro $99/year (10 hours)',
    pricingNotes: ['Storage is the only plan differentiator.'],
    reviewerAccess: 'Share links for client review.',
    selfHosted: false,
    sources: ['https://videoreview.pro/'],
  },
};

export const openFrameProfile = {
  name: 'OpenFrame',
  tagline: 'Fair-source video review and approval with hosted and self-hosted options.',
  pricingSummary: 'Self-hosted free · Hosted $10/mo after 7-day trial',
  trial: '7-day free trial on hosted plan',
  strengths: [
    'Timestamped text, voice, image, and drawn annotations',
    'Version compare with side-by-side review',
    'Approval requests with per-reviewer decisions',
    'Guest share links with optional password and expiry',
    'PDF/CSV comment exports',
    'Unlimited YouTube imports on hosted plan',
    'Self-host with Docker or use hosted cloud',
  ],
  bestFor: [
    'Freelancers and small teams shipping client cuts',
    'Studios that want open/fair-source and optional self-hosting',
    'Teams tired of vague email and WhatsApp feedback',
  ],
};
